# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Details.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRect
from richText import RichTextWindow

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 800)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listwgt_labelList = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwgt_labelList.sizePolicy().hasHeightForWidth())
        self.listwgt_labelList.setSizePolicy(sizePolicy)
        self.listwgt_labelList.setObjectName("listwgt_labelList")
        self.verticalLayout_2.addWidget(self.listwgt_labelList)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ledit_newLabel = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_newLabel.sizePolicy().hasHeightForWidth())
        self.ledit_newLabel.setSizePolicy(sizePolicy)
        self.ledit_newLabel.setObjectName("ledit_newLabel")
        self.horizontalLayout_2.addWidget(self.ledit_newLabel)
        self.btn_newLabel = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_newLabel.setObjectName("btn_newLabel")
        self.btn_newLabel.setSizePolicy(QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_2.addWidget(self.btn_newLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_Details = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_Details.setGeometry(QtCore.QRect(0, 0, 182, 437))
        self.scrollAreaWidgetContents_Details.setObjectName("scrollAreaWidgetContents_Details")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_Details)
        self.verticalLayout.setObjectName("verticalLayout")
        self.richTextWindow = RichTextWindow()
        self.richTextWindow.setMinimumHeight(500)
        self.verticalLayout.addWidget(self.richTextWindow)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_Details)
        self.horizontalLayout.addWidget(self.splitter)
        self.splitter.setCollapsible(1,False)
        self.splitter.setStretchFactor(0,3)
        self.splitter.setStretchFactor(1,7)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_newLabel.setText(_translate("Dialog", "新增标签"))
