# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_newDocument = QtWidgets.QPushButton(self.centralwidget)
        self.btn_newDocument.setObjectName("btn_newDocument")
        self.verticalLayout.addWidget(self.btn_newDocument)
        self.btn_editDocument = QtWidgets.QPushButton(self.centralwidget)
        self.btn_editDocument.setObjectName("btn_editDocument")
        self.verticalLayout.addWidget(self.btn_editDocument)
        self.btn_deleteDocument = QtWidgets.QPushButton(self.centralwidget)
        self.btn_deleteDocument.setObjectName("btn_deleteDocument")
        self.verticalLayout.addWidget(self.btn_deleteDocument)
        self.btn_exportDocument = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exportDocument.setObjectName("btn_exportDocument")
        self.verticalLayout.addWidget(self.btn_exportDocument)
        self.btn_inportDocument = QtWidgets.QPushButton(self.centralwidget)
        self.btn_inportDocument.setObjectName("btn_inportDocument")
        self.verticalLayout.addWidget(self.btn_inportDocument)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineedit_searchText = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_searchText.setObjectName("lineedit_searchText")
        self.horizontalLayout_2.addWidget(self.lineedit_searchText)
        self.cbbox_searchTerm = QtWidgets.QComboBox(self.centralwidget)
        self.cbbox_searchTerm.setObjectName("cbbox_searchTerm")
        self.horizontalLayout_2.addWidget(self.cbbox_searchTerm)
        self.btn_newTerm = QtWidgets.QPushButton(self.centralwidget)
        self.btn_newTerm.setObjectName("btn_newTerm")
        self.horizontalLayout_2.addWidget(self.btn_newTerm)
        self.btn_clearTerm = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clearTerm.setObjectName("btn_clearTerm")
        self.horizontalLayout_2.addWidget(self.btn_clearTerm)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_2.addWidget(self.btn_search)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.table_document = QtWidgets.QTableWidget(self.centralwidget)
        self.table_document.setObjectName("table_document")
        self.table_document.setColumnCount(0)
        self.table_document.setRowCount(0)
        self.verticalLayout_2.addWidget(self.table_document)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_newDocument.setText(_translate("MainWindow", "新增文献"))
        self.btn_editDocument.setText(_translate("MainWindow", "修改文献"))
        self.btn_deleteDocument.setText(_translate("MainWindow", "删除文献"))
        self.btn_exportDocument.setText(_translate("MainWindow","导出文件"))
        self.btn_inportDocument.setText(_translate("MainWindow","导入文件"))
        self.btn_newTerm.setText(_translate("MainWindow", "新增查询项"))
        self.btn_clearTerm.setText(_translate("MainWindow", "清空查询项"))
        self.btn_search.setText(_translate("MainWindow", "查询"))
